### ISSUE TITLE
milano.js.org

### ISSUE THREAD

**Issue by albertosantini** [milano-js/milano-js.github.io#8]
Maybe you are interested to the free domain in the subject.

You may give a look at js.org: http://dns.js.org/

torino.js.org is online. :)

**Comment by Granze** [comment]
That's really cool!
The fact is we already have milanojs.com and milanojs.org, and we are not using the second one because you can specify only one domain in the CNAME file on GH.

Anyway, thanks for the the advice, I'll use it for my projects for sure. ;)

**Comment by FezVrasta** [comment]
I think it would be much better to use .js.org, this would help other groups to create their website following a common pattern.

milano.js.org
torino.js.org
catania.js.org

and so on

**Comment by Granze** [comment]
Apart from what I wrote before, there are a couple of other aspects to consider:

- milanojs.com and milanojs.org are second level domains that I own and I can manage. milano.js.org is a subdomain owned by a third part that can shut down his service tomorrow.
- milano.js.org works only on Github Pages, this means that I'll not be able to host my website elsewhere if I want to.
- you can't "force" all the JS user groups to follow this pattern.
- there is no point to change a well known website address after two years without a good reason.

So, honestly I can only see those disadvantages here but no advantages to make the switch.

I'm missing something?

**Comment by FezVrasta** [comment]
About the pattern, the idea behind it was to provide a repository on GitHub which people can easily fork to create their own JS groups for their cities. I think it would be really nice.

**Comment by Granze** [comment]
Ok, this is a nice idea for sure and it can be useful for new JS user groups.
But still, there's no point for us to switch domain.

P.S. I'll introduce a "website" section in the [city-js repo](https://github.com/milano-js/city-js) so at least people will know about http://dns.js.org/
